module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-container": "#4d8eff",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary": "#005ac2",
        "on-error": "#690005",
        "on-surface-variant": "#c2c6d6",
        "surface-container-high": "#2a2a2a",
        "outline": "#8c909f",
        "on-primary": "#002e6a",
        "inverse-surface": "#e2e2e2",
        "on-tertiary-fixed": "#311400",
        "on-surface": "#e2e2e2",
        "error": "#ffb4ab",
        "on-background": "#e2e2e2",
        "surface-bright": "#393939",
        "on-primary-container": "#00285d",
        "surface-variant": "#353535",
        "surface": "#131313",
        "outline-variant": "#424754",
        "surface-container-highest": "#353535",
        "on-secondary-container": "#aeb9d0",
        "inverse-on-surface": "#303030",
        "secondary": "#bcc7de",
        "on-secondary": "#263143",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#d8e3fb",
        "primary": "#adc6ff",
        "on-secondary-fixed": "#111c2d",
        "secondary-fixed-dim": "#bcc7de",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-fixed-variant": "#723600",
        "surface-tint": "#adc6ff",
        "tertiary": "#ffb786",
        "on-primary-fixed": "#001a42",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-container": "#461f00",
        "surface-dim": "#131313",
        "surface-container": "#1f1f1f",
        "surface-container-low": "#1b1b1b",
        "tertiary-container": "#df7412",
        "error-container": "#93000a",
        "background": "#000000",
        "primary-fixed": "#d8e2ff",
        "secondary-container": "#3e495d",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#502400"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "8px",
        "sm": "12px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "md": "20px",
        "xl": "48px",
        "lg": "32px",
        "margin-desktop": "40px",
        "base": "4px"
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "label-caps": ["Geist"],
        "label-mono": ["Geist"],
        "body-sm": ["Hanken Grotesk"]
      },
      fontSize: {
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-mono": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
